DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzIzMzEwMTc5LCJ1c2VySWQiOjJ9.4qlFy0EjZF4v-6LSpULWG0tADkuFXz1BPZ_9RQKyr20